### ISSUE TITLE
When mouse on popup posframe, unable to execute transient command

### ISSUE THREAD

**Issue by stardiviner** [yanghaoxie/transient-posframe#2]
R.T

Maybe need to add some workaround.

**Comment by yanghaoxie** [comment]
Does this issue relate to the issue of `posframe`? I found flowing description from `posframe` homepage [Customizing mouse pointer control](https://github.com/tumashu/posframe#org5706c29).

```
Customizing mouse pointer control

By default, posframe moves the pointer to point (0,0) in the frame,
as a way to address an issue with mouse focus.
To disable this feature, add this to your init.el:

(setq posframe-mouse-banish nil)
```

**Comment by stardiviner** [comment]
I already set the option to `t`. Still have this problem.
